# Page settings

baseURL = "http://benmaier.org/"
languageCode = "en"
title = "Ben F. Maier"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-117120019-1"






[params]
    author = "Ben F. Maier"
    description = "A minimal pool of information about Ben F. Maier"


    primaryColor = "#137752"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Ben F. Maier"
        tagline = "Complex Systems Research and Data Science"
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "Berlin"

        #[[params.contact.list]]
        #icon = "fas fa-phone-square"
        #url = "tel:#"
        #text = "0123 4567 890"
        [[params.contact.list]]
        icon = "fa fa-id-badge"
        url = "CV"
        text = "Full CV"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "contact@benmaier.org"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "benmaier.org"







    [params.skills]
        enable = false

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "JavaScript/Angular/React/Vue"
        [[params.skills.list.items]]
        details = "Python/Ruby/PHP"
        [[params.skills.list.items]]
        details = "Node.js/ASP.NET"
        [[params.skills.list.items]]
        details = "PostgreSQL/MySQL"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Design and implement database structures"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "PhD in Theoretical Physics"
        university = "Humboldt University of Berlin, Robert Koch Institute"
        dates = "2015 - 2019"
        [[params.education.list]]
        degree = "MSc in Physics"
        university = "Humboldt University of Berlin"
        dates = "2011 - 2014"
        [[params.education.list]]
        degree = "Erasmus exchange"
        university = "Utrecht University"
        dates = "2011 - 2012"
        [[params.education.list]]
        degree = "BSc in Physics"
        university = "Humboldt University of Berlin"
        dates = "2008 - 2011"








    [params.fellowships]
        enable = true

        [[params.fellowships.list]]
        name = "Add-on Fellow for Interdisciplinary Life Science"
        body = "Joachim Herz Stiftung"
        date = "2018 -"
        [[params.fellowships.list]]
        name = "Scholarship"
        body = "Studienstiftung des Deutschen Volkes"
        date = "2011 - 2014"








    [params.languages]
        enable = false

        [[params.languages.list]]
        name = "German"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"
        [[params.languages.list]]
        name = "French"
        level = "Basic"








    [params.interests]
        enable = false

        [[params.interests.list]]
        name = "Electronic music"
        [[params.interests.list]]
        name = "Algorithmic arts"








    [params.summary]
        enable = true
        text = "I'm Ben, a post-doctoral researcher mainly studying how human behavior influences the spread of infectious diseases, but with widespread interest and experience regarding Complex Systems, Network Theory, Data Science, educational outreach, and algorithmic arts. Having a background in Physics, I'm trained in analyzing and visualizing big data sets as well as searching for the fundamental mechanisms that shape a system's behavior. My current position is with [Dirk Brockmann](http://rocs.hu-berlin.de), professor for [Theoretical Biology](https://itb.biologie.hu-berlin.de/wiki/) at [Humboldt University of Berlin](http://hu-berlin.de) and the [Robert Koch Institute](http://rki.de). \n\n You're cordially invited to investigate my [full CV](CV) if you're interested in more information."








    [params.experience]
        enable = false

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "2019 - Present"
        company = "Google"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."
        [[params.experience.list.items]]
        details = "Etiam ultricies nisi vel augue."



    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."


    [params.information]
        enable = false


    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/benmaier"
        title = "benmaier"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/benjaminfrankmaier"
        title = "benjaminfrankmaier"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/BenFMaier"
        title = "@BenFMaier"
        [[params.social.list]]
        icon = "fa fa-user-graduate"
        url = "//scholar.google.com/citations?user=WRU4JG0AAAAJ"
        title = "Google Scholar"


    [params.footer]
        copyright = "Ben F. Maier, Impressum: Benjamin F. Maier, Robert Koch-Institut, Nordufer 20, 13353 Berlin"
