# Page settings

baseURL = "http://benmaier.org/"
languageCode = "en"
title = "Ben F. Maier"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-117120019-1"






[params]
    author = "Ben F. Maier"
    description = "A minimal pool of information about Ben F. maier"


    primaryColor = "#19a974"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Ben F. Maier"
        tagline = "Research and Consulting"
        avatar = "avatar.png"







    [params.contact]
        enable = true
        location = "Berlin"

        #[[params.contact.list]]
        #icon = "fas fa-phone-square"
        #url = "tel:#"
        #text = "0123 4567 890"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "contact@benmaier.org"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "www.benmaier.org"







    [params.skills]
        enable = false

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "JavaScript/Angular/React/Vue"
        [[params.skills.list.items]]
        details = "Python/Ruby/PHP"
        [[params.skills.list.items]]
        details = "Node.js/ASP.NET"
        [[params.skills.list.items]]
        details = "PostgreSQL/MySQL"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Design and implement database structures"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "PhD in Theoretical Physics"
        university = "Humboldt University of Berlin, Robert Koch Institute"
        dates = "2015 - 2019"
        [[params.education.list]]
        degree = "MSc in Physics"
        university = "Humboldt University of Berlin"
        dates = "2011 - 2014"
        [[params.education.list]]
        degree = "Erasmus exchange"
        university = "Utrecht University"
        dates = "2011 - 2012"
        [[params.education.list]]
        degree = "BSc in Physics"
        university = "Humboldt University of Berlin"
        dates = "2008 - 2011"








    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Add-on Fellow for Interdisciplinary Life Science"
        body = "Joachim Herz Stiftung"
        date = "2018 -"
        [[params.awards.list]]
        name = "Scholarship"
        body = "Studienstiftung des Deutschen Volkes"
        date = "2011 - 2014"








    [params.languages]
        enable = false

        [[params.languages.list]]
        name = "German"
        level = "Native"
        [[params.languages.list]]
        name = "English"
        level = "Professional"
        [[params.languages.list]]
        name = "French"
        level = "Basic"








    [params.interests]
        enable = false

        [[params.interests.list]]
        name = "Electronic Music"
        [[params.interests.list]]
        name = "Algorithmic Arts"








    [params.summary]
        enable = true
        text = "<!--more-->I'm Ben, a researcher mainly interested in how human behavior influences the spread of infectious diseases. My current employer is [Dirk Brockmann](rocs.hu-berlin.de), professor for Theoretical Biology at Humboldt University of Berlin and the Robert Koch Institute."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "2019 - Present"
        company = "Google"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."
        [[params.experience.list.items]]
        details = "Etiam ultricies nisi vel augue."

        [[params.experience.list]]
        title = "Lead Software Developer"
        dates = "2016 - 2019"
        company = "Apple"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
        [[params.experience.list.items]]
        details = "Lorem ipsum dolor sit amet, consectetuer."
        [[params.experience.list.items]]
        details = "Aenean commodo ligula eget dolor."

        [[params.experience.list]]
        title = "Senior Software Developer"
        dates = "2014 - 2016"
        company = "Dropbox"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Senior Developer"
        dates = "2013 - 2014"
        company = "Uber"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."

        [[params.experience.list]]
        title = "Backend Developer"
        dates = "2014 - 2016"
        company = "Amazon"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.experience.list]]
        title = "Frontend Developer"
        dates = "2013 - 2014"
        company = "Startup"
        details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."











    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Project Lorem Ipsum"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."

        [[params.projects.list]]
        title = "Project Sed Fringilla"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."

        [[params.projects.list]]
        title = "Project Praesent"
        meta = "Open Source"
        tagline = "You can use this section for your side projects. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim."










    [params.information]
        enable = true

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/benmaier"
        title = "benmaier"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/benjaminfrankmaier"
        title = "benjaminfrankmaier"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/BenFMaier"
        title = "@BenFMaier"





    [params.footer]
        copyright = "Ben F. Maier, Impressum: Benjamin F. Maier, Robert Koch-Institut, Nordufer 20, 13353 Berlin"
